### ISSUE TITLE
odd crashes with specific iwad + mod combination

### ISSUE THREAD

**Issue by staticanimal** [flathub/org.zdoom.GZDoom#64] opened 2023-12-23 23:33 UTC
crash occurs seemingly at total random. mostly worked fine throughout the first two episodes of ultimate doom, became more prevalent in map 4 of episode 3. not sure where specifically to post about this issue.
it might be important to note that i'm launching the game through a deck oriented doom launcher called "GZDeck"

platform: SteamOS 3.5.7
gzdoom flatpak version: g4.11.3-m
iwad: doomu.wad
loaded mods: voxel doom [cheello_voxels.zip]

screenshot of crash attached below

![20231221112935_1](https://github.com/flathub/org.zdoom.GZDoom/assets/15201235/6d29c33f-3356-444e-8bca-2f8c3b507b52)

**Comment by Eonfge** [comment] 2024-05-02 06:42
Sorry for not commenting any earlier. I have no clue. Perhaps you can ask the Mod developers or the team behind GZDoom directly.

**Comment by Eonfge** [comment] 2024-12-20 13:08
Closing this one since I've never been able to reproduce it, and the stack trace make me think it's drivers (RADV) related

**Closed by Eonfge** 2024-12-20 13:08 UTC
